[package]
name = "polaris_control"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vehicle_control_node"
path = "src/main.rs"

[dependencies]
r2r = "0.9"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
log = "0.4"
env_logger = "0.11"
